Repository Bearsampp/Bearsampp, pull requests merged in 2022-09, with the labels that each got.

#195 Remove PHP5 code from Alias files
  base/alias/adminer.conf
  base/alias/gitlist.conf
  base/alias/phpmemadmin.conf
  base/alias/phpmyadmin.conf
  base/alias/phppgadmin.conf
  base/alias/webgrind.conf
Labels: bug :bug:

#197 Change icon in restart
  README.md
  core/libs/php/php-win.exe
  core/libs/php/php.exe
Labels: enhancement :sparkles:

#206 fix for phpmyadmin in localhost webpage
  core/resources/homepage/tpls/hp.index.summary.php
Labels: bug :bug:

#207 Update nssm core to 2.24
  core/libs/nssm/ChangeLog.txt
  core/libs/nssm/README.txt
  core/libs/nssm/nssm.exe
Labels: enhancement :sparkles:

#221 Remove seemingly unused lib
  core/libs/markdown/1.0.2/markdown.php
  core/libs/markdown/1.7.0/Markdown.php
  core/libs/markdown/1.7.0/MarkdownExtra.php
  core/libs/markdown/1.7.0/MarkdownInterface.php
Labels: enhancement :sparkles:

#223 Changes to bootstra 5.2
  core/resources/homepage/ajax/ajax.apache.php
  core/resources/homepage/ajax/ajax.filezilla.php
  core/resources/homepage/ajax/ajax.mailhog.php
  core/resources/homepage/ajax/ajax.mariadb.php
  core/resources/homepage/ajax/ajax.memcached.php
  core/resources/homepage/ajax/ajax.mysql.php
  core/resources/homepage/ajax/ajax.nodejs.php
  core/resources/homepage/ajax/ajax.php.php
  core/resources/homepage/ajax/ajax.postgresql.php
  core/resources/homepage/ajax/ajax.summary.php
  core/resources/homepage/css/app.css
  core/resources/homepage/homepage.php
  core/resources/homepage/img/svn.png
  core/resources/homepage/libs/bootstrap/bootstrap.min.css
  core/resources/homepage/libs/bootstrap/bootstrap.min.js
  core/resources/homepage/libs/bootstrap/fonts/glyphicons-halflings-regular.eot
  core/resources/homepage/libs/bootstrap/fonts/glyphicons-halflings-regular.svg
  core/resources/homepage/libs/bootstrap/fonts/glyphicons-halflings-regular.ttf
  core/resources/homepage/libs/bootstrap/fonts/glyphicons-halflings-regular.woff
  core/resources/homepage/libs/bootstrap/popper.min.js
  core/resources/homepage/tpls/hp.index.apache.php
  core/resources/homepage/tpls/hp.index.filezilla.php
  core/resources/homepage/tpls/hp.index.mailhog.php
  core/resources/homepage/tpls/hp.index.mariadb.php
  core/resources/homepage/tpls/hp.index.memcached.php
  core/resources/homepage/tpls/hp.index.mysql.php
  core/resources/homepage/tpls/hp.index.nodejs.php
  core/resources/homepage/tpls/hp.index.php
  core/resources/homepage/tpls/hp.index.php.php
  core/resources/homepage/tpls/hp.index.postgresql.php
  core/resources/homepage/tpls/hp.index.summary.php
  core/resources/homepage/tpls/hp.phpinfo.php
Labels: enhancement :sparkles:

#236 Sort versions properly
  core/classes/class.util.php
Labels: enhancement :sparkles:

#241 removes inline styles
  core/resources/homepage/ajax/ajax.apache.php
  core/resources/homepage/ajax/ajax.filezilla.php
  core/resources/homepage/ajax/ajax.mailhog.php
  core/resources/homepage/ajax/ajax.mariadb.php
  core/resources/homepage/ajax/ajax.memcached.php
  core/resources/homepage/ajax/ajax.mysql.php
  core/resources/homepage/ajax/ajax.nodejs.php
  core/resources/homepage/ajax/ajax.php.php
  core/resources/homepage/ajax/ajax.postgresql.php
  core/resources/homepage/ajax/ajax.summary.php
  core/resources/homepage/css/app.css
  core/resources/homepage/tpls/hp.index.summary.php
Labels: enhancement :sparkles:

#242 Converts linux / paths to windows \ paths
  build.xml
Labels: feature request :bulb:
